---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerospike-proximus.fullname" . }}
  labels:
    app:  {{ include "aerospike-proximus.fullname" . }}
    {{- include "aerospike-proximus.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $k := .Values.proximusConfig.service.ports | keys }}
    - name: {{ printf "svc-%s" $k }}
      port: {{ $k }}
      {{- end -}}
    {{- range $k := .Values.proximusConfig.manage.ports | keys }}
    - name: {{ printf "manage-%s" $k }}
      port: {{ $k }}
      {{- end -}}
    {{- range $k := .Values.proximusConfig.interconnect.ports | keys }}
    - name: {{ printf "interc-%s" $k }}
      port: {{ $k }}
      {{- end }}
  selector:
    app:  {{ include "aerospike-proximus.fullname" . }}
    {{- include "aerospike-proximus.selectorLabels" . | nindent 4 }}

---
{{- if and .Values.service.enabled  -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "aerospike-proximus.labels" . | nindent 4 }}
    app:  {{ include "aerospike-proximus.fullname" . }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "aerospike-proximus.fullname" . }}-lb
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs: {{ toYaml .Values.service.externalIPs | nindent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
{{- end }}
{{- if hasKey .Values.service "allocateLoadBalancerNodePorts" }}
  allocateLoadBalancerNodePorts: {{ .Values.service.allocateLoadBalancerNodePorts }}
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
{{- end }}
{{- if .Values.service.healthCheckNodePort }}
  healthCheckNodePort: {{ .Values.service.healthCheckNodePort }}
{{- end }}
{{- if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version -}}
{{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
{{- end }}
{{- if .Values.service.ipFamilies }}
  ipFamilies: {{ toYaml .Values.service.ipFamilies | nindent 4 }}
{{- end }}
{{- end }}
  ports:
  {{- range $v := .Values.service.ports }}
    - name: {{ $v.name }}
      port: {{ $v.port }}
      protocol: TCP
    {{- if ($v.targetPort) }}
      targetPort: {{ $v.targetPort }}
    {{- end }}
    {{- if and (semverCompare ">=1.20" $.Capabilities.KubeVersion.Version) ($v.appProtocol) }}
      appProtocol: {{ $v.appProtocol }}
    {{- end }}
  {{- end }}
  selector:
    app:  {{ include "aerospike-proximus.fullname" . }}
    {{- include "aerospike-proximus.selectorLabels" . | nindent 4 }}
{{- end }}
