replicaCount: 3

# Default Connector configuration.
# Visit: https://docs.aerospike.com/connect/esp/from-asdb/configuring
connectorConfig:
  service:
    # TLS setup for communication between Aerospike server (XDR) and the
    # connector.
    # Use the TLS certificates and keys specific to your setup.
    # See: https://docs.aerospike.com/connect/esp/from-asdb/configuring/service#configuring-tls
    address: 0.0.0.0
    port: 8901
    manage:
      address: 0.0.0.0
      port: 8902
    io-threads: 100
    worker-threads: 100
    max-concurrent-requests: 100000

  routing:
    mode: static-multi-destination
    destinations:
      - dc1

  record-ordering:
    enable: false
    lut-cache-ttl-seconds: 30

  # See: https://docs.aerospike.com/connect/esp/from-asdb/configuring/destinations
  destinations:
    dc1:
      urls:
        - https://connector.aerospike.com:8443
      tls:
        trust-store:
          store-file: secrets/tls-certs/svc.cluster.local.truststore.jks
          store-password-file: secrets/tls-certs/storepass
      health-check:
        call-timeout: 5100
      connect-timeout: 5000
      connection-ttl: 300000
      max-connections-per-endpoint: 20
      call-timeout: 5100
      protocol: HTTP_2
      http2-max-concurrent-streams: 100

  namespaces:
    test:
      custom-transformer:
        class: com.aerospike.connect.outbound.TestOutboundCustomTransformer

  # The logging properties.
  logging:
    enable-console-logging: true

# List of secrets containing TLS certificates (required for HTTPS connections)
connectorSecrets:
  - tls-certs

# List of initContainers to be added for each connector pod.
# Can be used to copy custom code plugins jars to /opt/aerospike-esp-outbound-init
initContainers:
  - name: aerospike-esp-outbound-init
    image: "aerospike/aerospike-connect-custom-transformers:1.0.0" # Image containing custom code plugins jars
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    # Update args to copy all the jars from init container to emptyDir volume path
    args:
      - |
        set -e
        cp -r /etc/aerospike-connector-custom-transformers/aerospike-esp-outbound-custom-transformers.jar /opt/aerospike-esp-outbound-init
    volumeMounts:
      - name: aerospike-esp-outbound-init
        mountPath: /opt/aerospike-esp-outbound-init
